[package]
name = "canic-core"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = "README.md"
documentation = "https://docs.rs/canic-core"
homepage = "https://github.com/dragginzgame/canic"
repository = "https://github.com/dragginzgame/canic"
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[features]
default = []
ic = []

[dependencies]
candid = { workspace = true }
canic-cdk = { workspace = true }
canic-macros = { workspace = true }
canic-memory = { workspace = true }
canic-types = { workspace = true }
canic-utils = { workspace = true }
ctor = { workspace = true }
derive_more = { workspace = true }
ic-canister-sig-creation = { workspace = true }
ic-cdk = { workspace = true }
ic-signature-verification = { workspace = true }
ic-stable-structures = { workspace = true }
minicbor-serde = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
futures = "0.3"

[[bench]]
name = "serialize"
harness = false

[lints]
workspace = true
