[package]
name = "canic-core"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[dependencies]
candid = { workspace = true }
canic-cdk = { workspace = true }
convert_case = { workspace = true }
derive_more = { workspace = true }
ic-cdk = { workspace = true }
minicbor-serde = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
base32 = { workspace = true }
hex = { workspace = true }
ulid = { workspace = true }
crc32fast = { workspace = true }
defer = { workspace = true }
num-traits = { workspace = true }
serde_bytes = { workspace = true }
thiserror = { workspace = true }
tinyrand = { workspace = true }
xxhash-rust = { workspace = true }

[lints]
workspace = true
