[package]
name = "canic-core"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = "README.md"
documentation = "https://docs.rs/canic-core"
homepage = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[dependencies]
candid = { workspace = true }
canic-cdk = { workspace = true }
canic-memory = { workspace = true }
canic-utils = { workspace = true }
ctor = { workspace = true }
derive_more = { workspace = true }
ic-canister-sig-creation = { workspace = true }
ic-cdk = { workspace = true }
ic-signature-verification = { workspace = true }
ic-stable-structures = { workspace = true }
num-traits = { workspace = true }
remain = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[build-dependencies]
candid = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
futures = "0.3"

[[bench]]
name = "serialize"
harness = false

[lints]
workspace = true
