[package]
name = "canic-utils"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[dependencies]
convert_case = { workspace = true }
derive_more = { workspace = true }
ic-cdk = { workspace = true }
sha2 = { workspace = true }
tinyrand = { workspace = true }
xxhash-rust = { workspace = true }

[lints]
workspace = true
