[package]
name = "sharding_root_stub"
edition = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic = { workspace = true }
ic-cdk = { workspace = true }
