[package]
name = "canic"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[features]
default = []
ic = []

[dependencies]
base32 = { workspace = true }
candid = { workspace = true }
canic-cdk = { workspace = true }
canic-utils = { workspace = true }
crc32fast = { workspace = true }
ctor = { workspace = true }
defer = { workspace = true }
derive_more = { workspace = true }
hex = { workspace = true }
ic-canister-sig-creation = { workspace = true }
ic-cdk = { workspace = true }
ic-signature-verification = { workspace = true }
ic-stable-structures = { workspace = true }
icrc-ledger-types = { workspace = true }
minicbor-serde = { workspace = true }
num-traits = { workspace = true }
remain = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }
ulid = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "serialize"
harness = false

[lints]
workspace = true
