[package]
name = "canic"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = { workspace = true }
documentation = "https://docs.rs/canic"
homepage = "https://github.com/dragginzgame/canic"
repository = "https://github.com/dragginzgame/canic"
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[features]
default = []
ic = ["canic-core/ic"]

[dependencies]
candid = { workspace = true }
canic-core = { workspace = true }
canic-types = { workspace = true }
canic-macros = { workspace = true }
canic-cdk = { workspace = true }
ic-cdk = { workspace = true }
canic-memory = { workspace = true }
canic-utils = { workspace = true }

[lints]
workspace = true
