[package]
name = "canic"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
description = { workspace = true }
readme = "README.md"
documentation = "https://docs.rs/canic"
homepage = { workspace = true }
repository = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }
publish = true

[dependencies]
candid = { workspace = true }
canic-cdk = { workspace = true }
canic-core = { workspace = true }
canic-dsl = { workspace = true }
canic-memory = { workspace = true }
canic-utils = { workspace = true }
ic-cdk = { workspace = true }

[build-dependencies]
canic-core = { workspace = true }

[dev-dependencies]
canic-internal = { path = "../canic-internal" }
canic-testkit = { path = "../canic-testkit" }

[lints]
workspace = true
