controllers = []
app_directory = []

[auth.delegated_tokens]
enabled = true
ecdsa_key_name = "test_key_1"

[subnets.prime]

[subnets.prime.canisters.root]
kind = "root"

[subnets.prime.canisters.user_shard]
kind = "shard"
