[package]
name = "intent_authority"
edition = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = { workspace = true }
canic-core = { workspace = true }
ic-cdk = { workspace = true }

[lints]
workspace = true
