controllers = []
app_directory = []

[auth.delegated_tokens]
enabled = true
ecdsa_key_name = "test_key_1"

[subnets.prime]
auto_create = ["signer"]

[subnets.prime.canisters.root]
kind = "root"

[subnets.prime.canisters.signer]
kind = "singleton"
initial_cycles = "1T"
